export const TILE_SIZE = 32;
export const WORLD_WIDTH = 1536;
export const WORLD_HEIGHT = 400;

export enum BlockType {
  Air = 0,
  Dirt = 1,
  Grass = 2,
  Stone = 3,
  Wood = 4,
  Leaves = 5,
  Planks = 6,
  Glass = 7,
  Lava = 8,
  Torch = 9,
  Sand = 10,
  Water = 11,
  CoalOre = 12,
  IronOre = 13,
  GoldOre = 14,
  DiamondOre = 15,
  Furnace = 16,
  Coal = 17,
  IronIngot = 18,
  GoldIngot = 19,
  Diamond = 20,
  AdminBrick = 21,
  QuestNPC = 22,
  Merchant = 30,
  Wire = 31,
  PressurePlate = 32,
  DoorOpen = 33,
  TNT = 34,
  Farmland = 23,
  CarrotCrop1 = 24,
  CarrotCrop2 = 25,
  CarrotCrop3 = 26,
  Chest = 27,
  Platform = 28,
  Door = 29,
  WoodPickaxe = 100,
  StonePickaxe = 101,
  WoodSword = 102,
  Fists = 103,
  IronPickaxe = 104,
  IronSword = 105,
  WoodHoe = 106,
  Bow = 109,
  Arrow = 110,
  GrapplingHook = 111,
  WoodAxe = 120,
  StoneAxe = 121,
  IronAxe = 122,
  Skeleton = 300,
  Creeper = 301,
  Gun = 302,
  Bullet = 303,
  Grenade = 304,
  StoneHoe = 107,
  IronHoe = 108,
  CarrotSeed = 200,
  Carrot = 201,
  Apple = 202,
  Snow = 203,
  Ice = 204,
  Cactus = 205,
  TreeSeed = 206,
  IronHelmet = 400,
  IronChestplate = 401,
  GoldHelmet = 407,
  GoldChestplate = 408,
  DiamondHelmet = 409,
  DiamondChestplate = 410,
  Gunpowder = 402,
  Bone = 403,
  CorruptedStone = 35,
  CorruptedGrass = 36,
  BossGolem = 404,
  BossDrop = 405,
  MagicStaff = 406,
  DiamondSword = 411,
  GoldSword = 412,
  StoneSword = 413,
  GuideNPC = 414,
  GoblinNPC = 415,
  WizardNPC = 416,
  DurelNPC = 417,
  WizardStaff = 418,
  BlueCrystal = 419,
  XpOrb = 999
}

export const BlockColors: Record<BlockType, string> = {
  [BlockType.Air]: 'transparent',
  [BlockType.Dirt]: '#5D4037',
  [BlockType.Grass]: '#388E3C', 
  [BlockType.Stone]: '#757575',
  [BlockType.Wood]: '#4E342E',
  [BlockType.Leaves]: 'rgba(46, 125, 50, 0.9)',
  [BlockType.Planks]: '#8D6E63',
  [BlockType.Glass]: 'rgba(255, 255, 255, 0.4)',
  [BlockType.Lava]: '#FF5722',
  [BlockType.Torch]: '#FFC107',
  [BlockType.Sand]: '#F4A460',
  [BlockType.Water]: 'rgba(33, 150, 243, 0.6)',
  [BlockType.CoalOre]: '#424242',
  [BlockType.IronOre]: '#BCAAA4',
  [BlockType.GoldOre]: '#FFD54F',
  [BlockType.DiamondOre]: '#4DD0E1',
  [BlockType.Furnace]: '#616161',
  [BlockType.Coal]: '#1c1c1c',
  [BlockType.IronIngot]: '#E0E0E0',
  [BlockType.GoldIngot]: '#FBC02D',
  [BlockType.Diamond]: '#00ACC1',
  [BlockType.AdminBrick]: '#37474F',
  [BlockType.BlueCrystal]: '#1E88E5',
  [BlockType.QuestNPC]: '#FF4081',
  [BlockType.Merchant]: '#9C27B0',
  [BlockType.Farmland]: '#4E342E',
  [BlockType.CarrotCrop1]: '#81C784',
  [BlockType.CarrotCrop2]: '#66BB6A',
  [BlockType.CarrotCrop3]: '#2E7D32',
  [BlockType.Chest]: '#795548', 
  [BlockType.Platform]: '#8D6E63',
  [BlockType.Door]: '#4E342E',
  [BlockType.WoodPickaxe]: '#A1887F', 
  [BlockType.StonePickaxe]: '#757575',
  [BlockType.WoodSword]: '#BDBDBD',
  [BlockType.Fists]: 'transparent', 
  [BlockType.IronPickaxe]: '#616161',
  [BlockType.IronSword]: '#9E9E9E',
  [BlockType.WoodHoe]: '#8D6E63',
  [BlockType.Bow]: '#5D4037',
  [BlockType.Arrow]: '#FFFFFF',
  [BlockType.WoodAxe]: '#A1887F',
  [BlockType.StoneAxe]: '#757575',
  [BlockType.IronAxe]: '#616161',
  [BlockType.Skeleton]: '#E0E0E0',
  [BlockType.Creeper]: '#4CAF50',
  [BlockType.TNT]: '#D32F2F',
  [BlockType.Gun]: '#424242',
  [BlockType.Bullet]: '#FFC107',
  [BlockType.Grenade]: '#2E7D32',
  [BlockType.Wire]: '#D50000',
  [BlockType.PressurePlate]: '#616161',
  [BlockType.DoorOpen]: '#4E342E',
  [BlockType.StoneHoe]: '#9E9E9E',
  [BlockType.IronHoe]: '#E0E0E0',
  [BlockType.CarrotSeed]: '#D7CCC8',
  [BlockType.Carrot]: '#2E7D32',
  [BlockType.Apple]: '#F44336',
  [BlockType.Snow]: '#FFFFFF',
  [BlockType.Ice]: '#B3E5FC',
  [BlockType.Cactus]: '#43A047',
  [BlockType.IronHelmet]: '#9E9E9E',
  [BlockType.IronChestplate]: '#BDBDBD',
  [BlockType.GoldHelmet]: '#FFD54F',
  [BlockType.GoldChestplate]: '#FBC02D',
  [BlockType.DiamondHelmet]: '#4DD0E1',
  [BlockType.DiamondChestplate]: '#00ACC1',
  [BlockType.Gunpowder]: '#757575',
  [BlockType.Bone]: '#FFFFFF',
  [BlockType.CorruptedStone]: '#311B92',
  [BlockType.CorruptedGrass]: '#4A148C',
  [BlockType.BossGolem]: '#1A237E',
  [BlockType.BossDrop]: '#FFD700',
    [BlockType.MagicStaff]: '#9C27B0',
  [BlockType.DiamondSword]: '#00BCD4',
  [BlockType.GoldSword]: '#FFD700',
  [BlockType.StoneSword]: '#9E9E9E',
  [BlockType.GuideNPC]: '#FFC107',
  [BlockType.GoblinNPC]: '#4CAF50',
  [BlockType.WizardNPC]: '#9C27B0',
  [BlockType.DurelNPC]: '#F44336',
  [BlockType.WizardStaff]: '#673AB7',
  [BlockType.TreeSeed]: '#4CAF50',
  [BlockType.GrapplingHook]: '#455A64',
  [BlockType.XpOrb]: '#00FF00'
};

export const SolidBlocks = new Set([
  BlockType.Dirt, BlockType.Grass, BlockType.Stone,
  BlockType.Planks, BlockType.Glass,
  BlockType.Sand, BlockType.CoalOre, BlockType.IronOre, BlockType.GoldOre, 
  BlockType.DiamondOre, BlockType.Furnace, BlockType.Snow, BlockType.Ice, BlockType.AdminBrick, BlockType.BlueCrystal, 
  BlockType.Farmland, BlockType.Chest
]);

export const BlockHardness: Record<BlockType, number> = {
  [BlockType.Air]: 0,
  [BlockType.Dirt]: 1,
  [BlockType.Grass]: 1,
  [BlockType.Stone]: 5,
  [BlockType.Wood]: 3,
  [BlockType.Leaves]: 0.5,
  [BlockType.Planks]: 2,
  [BlockType.Glass]: 1,
  [BlockType.Lava]: 0,
  [BlockType.Torch]: 0,
  [BlockType.Sand]: 1,
  [BlockType.Water]: 0,
  [BlockType.CoalOre]: 6,
  [BlockType.IronOre]: 8,
  [BlockType.GoldOre]: 8,
  [BlockType.DiamondOre]: 10,
  [BlockType.Furnace]: 5,
  [BlockType.Coal]: 0,
  [BlockType.IronIngot]: 0,
  [BlockType.GoldIngot]: 0,
  [BlockType.Diamond]: 0,
  [BlockType.AdminBrick]: Infinity,
  [BlockType.BlueCrystal]: 8,
  [BlockType.QuestNPC]: Infinity,
  [BlockType.Merchant]: Infinity,
  [BlockType.Farmland]: 1,
  [BlockType.CarrotCrop1]: 0,
  [BlockType.CarrotCrop2]: 0,
  [BlockType.CarrotCrop3]: 0,
  [BlockType.Chest]: 3,
  [BlockType.Platform]: 1,
  [BlockType.Door]: 2,
  [BlockType.WoodPickaxe]: 0,
  [BlockType.StonePickaxe]: 0,
  [BlockType.WoodSword]: 0,
  [BlockType.Fists]: 0,
  [BlockType.IronPickaxe]: 0,
  [BlockType.IronSword]: 0,
  [BlockType.WoodHoe]: 0,
  [BlockType.Bow]: 0,
  [BlockType.Arrow]: 0,
  [BlockType.WoodAxe]: 0,
  [BlockType.StoneAxe]: 0,
  [BlockType.IronAxe]: 0,
  [BlockType.Skeleton]: 0,
  [BlockType.Creeper]: 0,
  [BlockType.TNT]: 1,
  [BlockType.Gun]: 0,
  [BlockType.Bullet]: 0,
  [BlockType.Grenade]: 0,
  [BlockType.Wire]: 0,
  [BlockType.PressurePlate]: 1,
  [BlockType.DoorOpen]: 2,
  [BlockType.StoneHoe]: 0,
  [BlockType.IronHoe]: 0,
  [BlockType.CarrotSeed]: 0,
  [BlockType.Carrot]: 0,
  [BlockType.Apple]: 0,
  [BlockType.Snow]: 0.5,
  [BlockType.Ice]: 1,
  [BlockType.Cactus]: 0.5,
  [BlockType.IronHelmet]: 0,
  [BlockType.IronChestplate]: 0,
  [BlockType.GoldHelmet]: 0,
  [BlockType.GoldChestplate]: 0,
  [BlockType.DiamondHelmet]: 0,
  [BlockType.DiamondChestplate]: 0,
  [BlockType.Gunpowder]: 0,
  [BlockType.Bone]: 0,
  [BlockType.CorruptedStone]: 15,
  [BlockType.CorruptedGrass]: 10,
  [BlockType.BossGolem]: 0,
  [BlockType.BossDrop]: 0,
    [BlockType.MagicStaff]: 0,
  [BlockType.DiamondSword]: 0,
  [BlockType.GoldSword]: 0,
  [BlockType.StoneSword]: 0,
  [BlockType.GuideNPC]: Infinity,
  [BlockType.GoblinNPC]: Infinity,
  [BlockType.WizardNPC]: Infinity,
  [BlockType.DurelNPC]: Infinity,
  [BlockType.WizardStaff]: 0,
  [BlockType.TreeSeed]: 0,
  [BlockType.GrapplingHook]: 0,
  [BlockType.XpOrb]: 0
};

export const PlatformBlocks = new Set([
  BlockType.Platform
]);

export const BlockNames: Record<BlockType, string> = {
  [BlockType.Air]: 'Air',
  [BlockType.Dirt]: 'Dirt',
  [BlockType.Grass]: 'Grass Block',
  [BlockType.Stone]: 'Stone',
  [BlockType.Wood]: 'Wood Log',
  [BlockType.Leaves]: 'Leaves',
  [BlockType.Planks]: 'Wood Planks',
  [BlockType.Glass]: 'Glass',
  [BlockType.Lava]: 'Lava',
  [BlockType.Torch]: 'Torch',
  [BlockType.Sand]: 'Sand',
  [BlockType.Water]: 'Water',
  [BlockType.CoalOre]: 'Coal Ore',
  [BlockType.IronOre]: 'Iron Ore',
  [BlockType.GoldOre]: 'Gold Ore',
  [BlockType.DiamondOre]: 'Diamond Ore',
  [BlockType.Furnace]: 'Furnace',
  [BlockType.Coal]: 'Coal',
  [BlockType.IronIngot]: 'Iron Ingot',
  [BlockType.GoldIngot]: 'Gold Ingot',
  [BlockType.Diamond]: 'Diamond',
  [BlockType.AdminBrick]: 'Admin Brick',
  [BlockType.QuestNPC]: 'Quest Guide',
  [BlockType.Merchant]: 'Merchant',
  [BlockType.Farmland]: 'Farmland',
  [BlockType.CarrotCrop1]: 'Carrot Seedling',
  [BlockType.CarrotCrop2]: 'Growing Carrot',
  [BlockType.CarrotCrop3]: 'Mature Carrot',
  [BlockType.Chest]: 'Chest',
  [BlockType.Platform]: 'Wooden Platform',
  [BlockType.Door]: 'Wooden Door',
  [BlockType.WoodPickaxe]: 'Wooden Pickaxe',
  [BlockType.StonePickaxe]: 'Stone Pickaxe',
  [BlockType.WoodSword]: 'Wooden Sword',
  [BlockType.Fists]: 'Fists',
  [BlockType.IronPickaxe]: 'Iron Pickaxe',
  [BlockType.IronSword]: 'Iron Sword',
  [BlockType.WoodHoe]: 'Wooden Hoe',
  [BlockType.Bow]: 'Bow',
  [BlockType.Arrow]: 'Arrow',
  [BlockType.WoodAxe]: 'Wooden Axe',
  [BlockType.StoneAxe]: 'Stone Axe',
  [BlockType.IronAxe]: 'Iron Axe',
  [BlockType.GrapplingHook]: 'Grappling Hook',
  [BlockType.Skeleton]: 'Skeleton',
  [BlockType.Creeper]: 'Creeper',
  [BlockType.TNT]: 'TNT',
  [BlockType.Gun]: 'Gun',
  [BlockType.Bullet]: 'Ammunition',
  [BlockType.Grenade]: 'Hand Grenade',
  [BlockType.Wire]: 'Redstone Wire',
  [BlockType.PressurePlate]: 'Pressure Plate',
  [BlockType.DoorOpen]: 'Open Door',
  [BlockType.StoneHoe]: 'Stone Hoe',
  [BlockType.IronHoe]: 'Iron Hoe',
  [BlockType.CarrotSeed]: 'Carrot Seeds',
  [BlockType.Carrot]: 'Carrot',
  [BlockType.Apple]: 'Apple',
  [BlockType.Snow]: 'Snow Block',
  [BlockType.Ice]: 'Ice',
  [BlockType.Cactus]: 'Cactus',
  [BlockType.TreeSeed]: 'Tree Seed',
  [BlockType.IronHelmet]: 'Iron Helmet',
  [BlockType.IronChestplate]: 'Iron Chestplate',
  [BlockType.GoldHelmet]: 'Gold Helmet',
  [BlockType.GoldChestplate]: 'Gold Chestplate',
  [BlockType.DiamondHelmet]: 'Diamond Helmet',
  [BlockType.DiamondChestplate]: 'Diamond Chestplate',
  [BlockType.Gunpowder]: 'Gunpowder',
  [BlockType.Bone]: 'Bone',
  [BlockType.CorruptedStone]: 'Corrupted Stone',
  [BlockType.CorruptedGrass]: 'Corrupted Grass',
  [BlockType.BossGolem]: 'Giant Golem',
  [BlockType.BossDrop]: 'Boss Relic',
  [BlockType.MagicStaff]: 'Magic Staff',
  [BlockType.DiamondSword]: 'Diamond Sword',
  [BlockType.GoldSword]: 'Gold Sword',
  [BlockType.StoneSword]: 'Stone Sword',
  [BlockType.GuideNPC]: 'Guide',
  [BlockType.GoblinNPC]: 'Goblin',
  [BlockType.WizardNPC]: 'Wizard',
  [BlockType.DurelNPC]: 'Durel',
  [BlockType.WizardStaff]: 'Wizard Staff',
  [BlockType.BlueCrystal]: 'Blue Crystal',
  [BlockType.XpOrb]: 'XP Orb'
};
