export const TILE_SIZE = 32;
export const WORLD_WIDTH = 256;
export const WORLD_HEIGHT = 128;

export enum BlockType {
  Air = 0,
  Dirt = 1,
  Grass = 2,
  Stone = 3,
  Wood = 4,
  Leaves = 5,
  Planks = 6,
  Glass = 7,
  Lava = 8,
  Torch = 9,
  Sand = 10,
  Water = 11,
  CoalOre = 12,
  IronOre = 13,
  GoldOre = 14,
  DiamondOre = 15,
  Furnace = 16,
  Coal = 17,
  IronIngot = 18,
  GoldIngot = 19,
  Diamond = 20,
  AdminBrick = 21,
  QuestNPC = 22,
  Farmland = 23,
  CarrotCrop1 = 24,
  CarrotCrop2 = 25,
  CarrotCrop3 = 26,
  Chest = 27,
  Platform = 28,
  Door = 29,
  WoodPickaxe = 100,
  StonePickaxe = 101,
  WoodSword = 102,
  Fists = 103,
  IronPickaxe = 104,
  IronSword = 105,
  WoodHoe = 106,
  StoneHoe = 107,
  IronHoe = 108,
  CarrotSeed = 200,
  Carrot = 201,
  Apple = 202
}

export const BlockColors: Record<BlockType, string> = {
  [BlockType.Air]: 'transparent',
  [BlockType.Dirt]: '#5D4037',
  [BlockType.Grass]: '#388E3C', 
  [BlockType.Stone]: '#757575',
  [BlockType.Wood]: '#4E342E',
  [BlockType.Leaves]: 'rgba(46, 125, 50, 0.9)',
  [BlockType.Planks]: '#8D6E63',
  [BlockType.Glass]: 'rgba(255, 255, 255, 0.4)',
  [BlockType.Lava]: '#FF5722',
  [BlockType.Torch]: '#FFC107',
  [BlockType.Sand]: '#F4A460',
  [BlockType.Water]: 'rgba(33, 150, 243, 0.6)',
  [BlockType.CoalOre]: '#424242',
  [BlockType.IronOre]: '#BCAAA4',
  [BlockType.GoldOre]: '#FFD54F',
  [BlockType.DiamondOre]: '#4DD0E1',
  [BlockType.Furnace]: '#616161',
  [BlockType.Coal]: '#1c1c1c',
  [BlockType.IronIngot]: '#E0E0E0',
  [BlockType.GoldIngot]: '#FBC02D',
  [BlockType.Diamond]: '#00ACC1',
  [BlockType.AdminBrick]: '#37474F',
  [BlockType.QuestNPC]: '#FF4081',
  [BlockType.Farmland]: '#4E342E',
  [BlockType.CarrotCrop1]: '#81C784',
  [BlockType.CarrotCrop2]: '#66BB6A',
  [BlockType.CarrotCrop3]: '#FF9800',
  [BlockType.Chest]: '#795548', // Brown wood color, similar to planks but distinct
  [BlockType.Platform]: '#8D6E63', // Same as planks for now
  [BlockType.Door]: '#4E342E',
  [BlockType.WoodPickaxe]: '#8D6E63',
  [BlockType.StonePickaxe]: '#9E9E9E',
  [BlockType.WoodSword]: '#A1887F',
  [BlockType.Fists]: 'transparent', // Rendered separately
  [BlockType.IronPickaxe]: '#E0E0E0',
  [BlockType.IronSword]: '#E0E0E0',
  [BlockType.WoodHoe]: '#8D6E63',
  [BlockType.StoneHoe]: '#9E9E9E',
  [BlockType.IronHoe]: '#E0E0E0',
  [BlockType.CarrotSeed]: '#D7CCC8',
  [BlockType.Carrot]: '#FF9800',
  [BlockType.Apple]: '#F44336'
};

export const SolidBlocks = new Set([
  BlockType.Dirt, BlockType.Grass, BlockType.Stone,
  BlockType.Wood, BlockType.Leaves, BlockType.Planks, BlockType.Glass,
  BlockType.Sand, BlockType.CoalOre, BlockType.IronOre, BlockType.GoldOre, 
  BlockType.DiamondOre, BlockType.Furnace, BlockType.AdminBrick, BlockType.QuestNPC,
  BlockType.Farmland, BlockType.Chest
]);

export const BlockHardness: Record<BlockType, number> = {
  [BlockType.Air]: 0,
  [BlockType.Dirt]: 1,
  [BlockType.Grass]: 1,
  [BlockType.Stone]: 5,
  [BlockType.Wood]: 3,
  [BlockType.Leaves]: 0.5,
  [BlockType.Planks]: 2,
  [BlockType.Glass]: 1,
  [BlockType.Lava]: 0,
  [BlockType.Torch]: 0,
  [BlockType.Sand]: 1,
  [BlockType.Water]: 0,
  [BlockType.CoalOre]: 6,
  [BlockType.IronOre]: 8,
  [BlockType.GoldOre]: 8,
  [BlockType.DiamondOre]: 10,
  [BlockType.Furnace]: 5,
  [BlockType.Coal]: 0,
  [BlockType.IronIngot]: 0,
  [BlockType.GoldIngot]: 0,
  [BlockType.Diamond]: 0,
  [BlockType.AdminBrick]: Infinity,
  [BlockType.QuestNPC]: Infinity,
  [BlockType.Farmland]: 1,
  [BlockType.CarrotCrop1]: 0,
  [BlockType.CarrotCrop2]: 0,
  [BlockType.CarrotCrop3]: 0,
  [BlockType.Chest]: 3,
  [BlockType.Platform]: 1,
  [BlockType.Door]: 2,
  [BlockType.WoodPickaxe]: 0,
  [BlockType.StonePickaxe]: 0,
  [BlockType.WoodSword]: 0,
  [BlockType.Fists]: 0,
  [BlockType.IronPickaxe]: 0,
  [BlockType.IronSword]: 0,
  [BlockType.WoodHoe]: 0,
  [BlockType.StoneHoe]: 0,
  [BlockType.IronHoe]: 0,
  [BlockType.CarrotSeed]: 0,
  [BlockType.Carrot]: 0,
  [BlockType.Apple]: 0
};

export const PlatformBlocks = new Set([
  BlockType.Platform
]);

export const BlockNames: Record<BlockType, string> = {
  [BlockType.Air]: 'Air',
  [BlockType.Dirt]: 'Dirt',
  [BlockType.Grass]: 'Grass Block',
  [BlockType.Stone]: 'Stone',
  [BlockType.Wood]: 'Wood Log',
  [BlockType.Leaves]: 'Leaves',
  [BlockType.Planks]: 'Wood Planks',
  [BlockType.Glass]: 'Glass',
  [BlockType.Lava]: 'Lava',
  [BlockType.Torch]: 'Torch',
  [BlockType.Sand]: 'Sand',
  [BlockType.Water]: 'Water',
  [BlockType.CoalOre]: 'Coal Ore',
  [BlockType.IronOre]: 'Iron Ore',
  [BlockType.GoldOre]: 'Gold Ore',
  [BlockType.DiamondOre]: 'Diamond Ore',
  [BlockType.Furnace]: 'Furnace',
  [BlockType.Coal]: 'Coal',
  [BlockType.IronIngot]: 'Iron Ingot',
  [BlockType.GoldIngot]: 'Gold Ingot',
  [BlockType.Diamond]: 'Diamond',
  [BlockType.AdminBrick]: 'Admin Brick',
  [BlockType.QuestNPC]: 'Quest NPC',
  [BlockType.Farmland]: 'Farmland',
  [BlockType.CarrotCrop1]: 'Carrot Crop (Stage 1)',
  [BlockType.CarrotCrop2]: 'Carrot Crop (Stage 2)',
  [BlockType.CarrotCrop3]: 'Carrot Crop (Stage 3)',
  [BlockType.Chest]: 'Chest',
  [BlockType.Platform]: 'Wooden Platform',
  [BlockType.Door]: 'Wooden Door',
  [BlockType.WoodPickaxe]: 'Wooden Pickaxe',
  [BlockType.StonePickaxe]: 'Stone Pickaxe',
  [BlockType.WoodSword]: 'Wooden Sword',
  [BlockType.Fists]: 'Fists',
  [BlockType.IronPickaxe]: 'Iron Pickaxe',
  [BlockType.IronSword]: 'Iron Sword',
  [BlockType.WoodHoe]: 'Wooden Hoe',
  [BlockType.StoneHoe]: 'Stone Hoe',
  [BlockType.IronHoe]: 'Iron Hoe',
  [BlockType.CarrotSeed]: 'Carrot Seeds',
  [BlockType.Carrot]: 'Carrot',
  [BlockType.Apple]: 'Apple'
};
