import fs from 'fs';
let code = fs.readFileSync('src/lib/constants.ts', 'utf8');

const newColors = `export const BlockColors: Record<BlockType, string> = {
  [BlockType.Air]: 'transparent',
  [BlockType.Dirt]: '#3E2723', 
  [BlockType.Grass]: '#424242', 
  [BlockType.Stone]: '#616161', 
  [BlockType.Wood]: '#455A64', 
  [BlockType.Leaves]: 'rgba(158, 158, 158, 0.4)', 
  [BlockType.Planks]: '#795548', 
  [BlockType.Glass]: 'rgba(224, 224, 224, 0.3)', 
  [BlockType.Lava]: '#7CB342', 
  [BlockType.Torch]: '#FDD835', 
  [BlockType.Sand]: '#757575', 
  [BlockType.Water]: 'rgba(76, 175, 80, 0.4)', 
  [BlockType.CoalOre]: '#212121', 
  [BlockType.IronOre]: '#9E9E9E', 
  [BlockType.GoldOre]: '#388E3C', 
  [BlockType.DiamondOre]: '#E0F7FA', 
  [BlockType.Furnace]: '#263238', 
  [BlockType.Coal]: '#424242', 
  [BlockType.IronIngot]: '#BDBDBD', 
  [BlockType.GoldIngot]: '#4CAF50', 
  [BlockType.Diamond]: '#FFFFFF', 
  [BlockType.AdminBrick]: '#212121', 
  [BlockType.QuestNPC]: '#D50000', 
  [BlockType.Farmland]: '#3E2723', 
  [BlockType.CarrotCrop1]: '#81C784', 
  [BlockType.CarrotCrop2]: '#4CAF50', 
  [BlockType.CarrotCrop3]: '#2E7D32', 
  [BlockType.Chest]: '#37474F', 
  [BlockType.Platform]: '#9E9E9E', 
  [BlockType.Door]: '#455A64', 
  [BlockType.WoodPickaxe]: '#A1887F', 
  [BlockType.StonePickaxe]: '#757575',
  [BlockType.WoodSword]: '#BDBDBD',
  [BlockType.Fists]: 'transparent', 
  [BlockType.IronPickaxe]: '#616161',
  [BlockType.IronSword]: '#9E9E9E',
  [BlockType.WoodHoe]: '#8D6E63',
  [BlockType.StoneHoe]: '#9E9E9E',
  [BlockType.IronHoe]: '#E0E0E0',
  [BlockType.CarrotSeed]: '#D7CCC8',
  [BlockType.Carrot]: '#2E7D32',
  [BlockType.Apple]: '#00BCD4' 
};`;

const newNames = `export const BlockNames: Record<BlockType, string> = {
  [BlockType.Air]: 'Air',
  [BlockType.Dirt]: 'Dirt',
  [BlockType.Grass]: 'Asphalt',
  [BlockType.Stone]: 'Concrete',
  [BlockType.Wood]: 'Steel Beam',
  [BlockType.Leaves]: 'Chainlink Fence',
  [BlockType.Planks]: 'Wooden Pallet',
  [BlockType.Glass]: 'Shattered Glass',
  [BlockType.Lava]: 'Toxic Sludge',
  [BlockType.Torch]: 'Street Lamp',
  [BlockType.Sand]: 'Gravel',
  [BlockType.Water]: 'Sewage Water',
  [BlockType.CoalOre]: 'Scrap Metal Cache',
  [BlockType.IronOre]: 'Gun Parts Stash',
  [BlockType.GoldOre]: 'Dirty Money Stash',
  [BlockType.DiamondOre]: 'Raw Product',
  [BlockType.Furnace]: 'Drug Lab / Workbench',
  [BlockType.Coal]: 'Scrap Metal',
  [BlockType.IronIngot]: 'Gun Parts',
  [BlockType.GoldIngot]: 'Laundered Cash',
  [BlockType.Diamond]: 'Pure Product',
  [BlockType.AdminBrick]: 'Vault Steel',
  [BlockType.QuestNPC]: 'The Boss',
  [BlockType.Farmland]: 'Grow Op Soil',
  [BlockType.CarrotCrop1]: 'Weed Sprout',
  [BlockType.CarrotCrop2]: 'Growing Weed',
  [BlockType.CarrotCrop3]: 'Mature Weed Plant',
  [BlockType.Chest]: 'Stash Safe',
  [BlockType.Platform]: 'Scaffolding',
  [BlockType.Door]: 'Security Door',
  [BlockType.WoodPickaxe]: 'Baseball Bat',
  [BlockType.StonePickaxe]: 'Crowbar',
  [BlockType.WoodSword]: 'Switchblade',
  [BlockType.Fists]: 'Bare Knuckles',
  [BlockType.IronPickaxe]: 'Glock 19',
  [BlockType.IronSword]: 'Machete',
  [BlockType.WoodHoe]: 'Rusty Shovel',
  [BlockType.StoneHoe]: 'Trowel',
  [BlockType.IronHoe]: 'Tactical Shovel',
  [BlockType.CarrotSeed]: 'Cannabis Seeds',
  [BlockType.Carrot]: 'Baggie of Weed',
  [BlockType.Apple]: 'Energy Drink'
};`;

code = code.replace(/export const BlockColors: Record<BlockType, string> = \{[\s\S]*?\};/, newColors);
code = code.replace(/export const BlockNames: Record<BlockType, string> = \{[\s\S]*?\};/, newNames);

fs.writeFileSync('src/lib/constants.ts', code);
