import fs from 'fs';
let code = fs.readFileSync('src/lib/constants.ts', 'utf8');

const newColors = `export const BlockColors: Record<BlockType, string> = {
  [BlockType.Air]: 'transparent',
  [BlockType.Dirt]: '#5D4037',
  [BlockType.Grass]: '#388E3C', 
  [BlockType.Stone]: '#757575',
  [BlockType.Wood]: '#4E342E',
  [BlockType.Leaves]: 'rgba(46, 125, 50, 0.9)',
  [BlockType.Planks]: '#8D6E63',
  [BlockType.Glass]: 'rgba(255, 255, 255, 0.4)',
  [BlockType.Lava]: '#FF5722',
  [BlockType.Torch]: '#FFC107',
  [BlockType.Sand]: '#F4A460',
  [BlockType.Water]: 'rgba(33, 150, 243, 0.6)',
  [BlockType.CoalOre]: '#424242',
  [BlockType.IronOre]: '#BCAAA4',
  [BlockType.GoldOre]: '#FFD54F',
  [BlockType.DiamondOre]: '#4DD0E1',
  [BlockType.Furnace]: '#616161',
  [BlockType.Coal]: '#1c1c1c',
  [BlockType.IronIngot]: '#E0E0E0',
  [BlockType.GoldIngot]: '#FBC02D',
  [BlockType.Diamond]: '#00ACC1',
  [BlockType.AdminBrick]: '#37474F',
  [BlockType.QuestNPC]: '#FF4081',
  [BlockType.Farmland]: '#4E342E',
  [BlockType.CarrotCrop1]: '#81C784',
  [BlockType.CarrotCrop2]: '#66BB6A',
  [BlockType.CarrotCrop3]: '#2E7D32',
  [BlockType.Chest]: '#795548', 
  [BlockType.Platform]: '#8D6E63',
  [BlockType.Door]: '#4E342E',
  [BlockType.WoodPickaxe]: '#A1887F', 
  [BlockType.StonePickaxe]: '#757575',
  [BlockType.WoodSword]: '#BDBDBD',
  [BlockType.Fists]: 'transparent', 
  [BlockType.IronPickaxe]: '#616161',
  [BlockType.IronSword]: '#9E9E9E',
  [BlockType.WoodHoe]: '#8D6E63',
  [BlockType.StoneHoe]: '#9E9E9E',
  [BlockType.IronHoe]: '#E0E0E0',
  [BlockType.CarrotSeed]: '#D7CCC8',
  [BlockType.Carrot]: '#2E7D32',
  [BlockType.Apple]: '#F44336'
};`;

const newNames = `export const BlockNames: Record<BlockType, string> = {
  [BlockType.Air]: 'Air',
  [BlockType.Dirt]: 'Dirt',
  [BlockType.Grass]: 'Grass Block',
  [BlockType.Stone]: 'Stone',
  [BlockType.Wood]: 'Wood Log',
  [BlockType.Leaves]: 'Leaves',
  [BlockType.Planks]: 'Wood Planks',
  [BlockType.Glass]: 'Glass',
  [BlockType.Lava]: 'Lava',
  [BlockType.Torch]: 'Torch',
  [BlockType.Sand]: 'Sand',
  [BlockType.Water]: 'Water',
  [BlockType.CoalOre]: 'Coal Ore',
  [BlockType.IronOre]: 'Iron Ore',
  [BlockType.GoldOre]: 'Gold Ore',
  [BlockType.DiamondOre]: 'Diamond Ore',
  [BlockType.Furnace]: 'Furnace',
  [BlockType.Coal]: 'Coal',
  [BlockType.IronIngot]: 'Iron Ingot',
  [BlockType.GoldIngot]: 'Gold Ingot',
  [BlockType.Diamond]: 'Diamond',
  [BlockType.AdminBrick]: 'Admin Brick',
  [BlockType.QuestNPC]: 'Quest Guide',
  [BlockType.Farmland]: 'Farmland',
  [BlockType.CarrotCrop1]: 'Carrot Seedling',
  [BlockType.CarrotCrop2]: 'Growing Carrot',
  [BlockType.CarrotCrop3]: 'Mature Carrot',
  [BlockType.Chest]: 'Chest',
  [BlockType.Platform]: 'Wooden Platform',
  [BlockType.Door]: 'Wooden Door',
  [BlockType.WoodPickaxe]: 'Wooden Pickaxe',
  [BlockType.StonePickaxe]: 'Stone Pickaxe',
  [BlockType.WoodSword]: 'Wooden Sword',
  [BlockType.Fists]: 'Fists',
  [BlockType.IronPickaxe]: 'Iron Pickaxe',
  [BlockType.IronSword]: 'Iron Sword',
  [BlockType.WoodHoe]: 'Wooden Hoe',
  [BlockType.StoneHoe]: 'Stone Hoe',
  [BlockType.IronHoe]: 'Iron Hoe',
  [BlockType.CarrotSeed]: 'Carrot Seeds',
  [BlockType.Carrot]: 'Carrot',
  [BlockType.Apple]: 'Apple'
};`;

code = code.replace(/export const BlockColors: Record<BlockType, string> = \{[\s\S]*?\};/, newColors);
code = code.replace(/export const BlockNames: Record<BlockType, string> = \{[\s\S]*?\};/, newNames);

fs.writeFileSync('src/lib/constants.ts', code);
